language: php
sudo: false
branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - schreiner.tim@gmail.com

before_install:
  - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - |
    composer require \
      typo3/cms-backend="$TYPO3_VERSION" \
      typo3/cms-recordlist="$TYPO3_VERSION" \
      typo3/cms-core="$TYPO3_VERSION" \
      typo3/cms-extbase="$TYPO3_VERSION" \
      typo3/cms-extensionmanager="$TYPO3_VERSION" \
      typo3/cms-fluid="$TYPO3_VERSION" \
      typo3/cms-frontend="$TYPO3_VERSION" \
      typo3/cms-install="$TYPO3_VERSION" \
      typo3/cms-scheduler="$TYPO3_VERSION" \
      typo3/cms-recordlist="$TYPO3_VERSION"
  - git checkout composer.json

script:
  - |
    echo;
    echo "Create LocalConfiguration.php";
    cat > .Build/Web/typo3conf/LocalConfiguration.php << EOF
    <?php
    return [];
    EOF
  - >
    echo;
    echo "Running php lint...";
    find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running PHP Coding Standards Fixer checks";
    .Build/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --diff --diff-format=udiff
  - >
    echo;
    echo "Running unit tests...";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running functional tests...";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional/

jobs:
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
  include:
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7

    - stage: 🚢 to TER
      if: tag IS present
      php: 7.0
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install ter client
            composer global require helhum/ter-client
            # Build extension files
            rm -rf Tests/
            rm .gitattributes
            rm .gitignore
            rm .php_cs.dist
            rm .travis.yml
            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload be_google_auth . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
